[package]
name = "ring"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maud = "*"
knuffel = "3"
miette = { version = "4.3", features = ["fancy"] }
url = { version = "2.3", features = ["serde"] }
