name: CI
on:
    push:
        branches: [ "main" ]
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: 'actions/checkout@v3.5.2'
        - uses: 'icepuma/rust-action@master'
          with:
            args: cargo run
        - uses: 'actions/upload-pages-artifact@v1.0.8'
          with:
            path: public
        - uses: 'actions/deploy-pages@v2.0.0'
# PLEASE STOP WITH THIS FUCKING YAML BULLSHIT THIS FORMAT IS PURE SHIT STOP USING IT FFS PLEASE
